<?php
if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( array(
    'key' => 'group_hero_section',
    'title' => 'Hero Section',
    'fields' => array(
        array(
            'key' => 'field_hero_tabs',
            'label' => 'Hero Section',
            'name' => 'hero_tabs',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_hero_image',
            'label' => 'Imagen Principal',
            'name' => 'hero_image',
            'type' => 'image',
            'return_format' => 'url',
            'preview_size' => 'medium',
            'library' => 'all',
            'mime_types' => 'jpg,jpeg,webp,png',
        ),
        array(
            'key' => 'field_hero_subtitle',
            'label' => 'Subtítulo',
            'name' => 'hero_subtitle',
            'type' => 'text',
            'default_value' => 'New Collection',
            'placeholder' => 'Ej: New Collection',
        ),
        array(
            'key' => 'field_hero_title',
            'label' => 'Título Principal',
            'name' => 'hero_title',
            'type' => 'text',
            'default_value' => 'Elegancia que habla por ti',
            'placeholder' => 'Ej: Elegancia que habla por ti',
        ),
        array(
            'key' => 'field_hero_description',
            'label' => 'Descripción',
            'name' => 'hero_description',
            'type' => 'textarea',
            'rows' => 3,
            'default_value' => 'Descubre piezas que definen tu estilo con sofisticación natural y confianza',
            'placeholder' => 'Descripción del hero...',
        ),
        array(
            'key' => 'field_hero_button_text',
            'label' => 'Texto del Botón',
            'name' => 'hero_button_text',
            'type' => 'text',
            'default_value' => 'Descubrir ahora',
            'placeholder' => 'Ej: Descubrir ahora',
        ),
        array(
            'key' => 'field_hero_button_url',
            'label' => 'Enlace del Botón',
            'name' => 'hero_button_url',
            'type' => 'text',
            'default_value' => '',
            'placeholder' => 'Ej: /shop o https://...',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => 'Campos para la sección Hero de la página de inicio',
) );

acf_add_local_field_group( array(
    'key' => 'group_newin_section',
    'title' => 'New In Section',
    'fields' => array(
        array(
            'key' => 'field_newin_tabs',
            'label' => 'New In Section',
            'name' => 'newin_tabs',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_newin_subtitle',
            'label' => 'Subtítulo',
            'name' => 'newin_subtitle',
            'type' => 'text',
            'default_value' => 'Lo Último',
            'placeholder' => 'Ej: Lo Último',
        ),
        array(
            'key' => 'field_newin_title',
            'label' => 'Título de la Sección',
            'name' => 'newin_title',
            'type' => 'text',
            'default_value' => 'New In',
            'placeholder' => 'Ej: New In',
        ),
        array(
            'key' => 'field_newin_button_text',
            'label' => 'Texto del Botón',
            'name' => 'newin_button_text',
            'type' => 'text',
            'default_value' => 'Ver todo',
            'placeholder' => 'Ej: Ver todo',
        ),
        array(
            'key' => 'field_newin_button_url',
            'label' => 'Enlace del Botón',
            'name' => 'newin_button_url',
            'type' => 'text',
            'default_value' => '',
            'placeholder' => 'Ej: /shop',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => 'Campos para la sección New In de la página de inicio',
) );

acf_add_local_field_group( array(
    'key' => 'group_historia_section',
    'title' => 'Nuestra Historia Section',
    'fields' => array(
        array(
            'key' => 'field_historia_tabs',
            'label' => 'Nuestra Historia',
            'name' => 'historia_tabs',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_historia_label',
            'label' => 'Etiqueta',
            'name' => 'historia_label',
            'type' => 'text',
            'default_value' => 'Nuestra historia',
            'placeholder' => 'Ej: Nuestra historia',
        ),
        array(
            'key' => 'field_historia_title',
            'label' => 'Título Principal',
            'name' => 'historia_title',
            'type' => 'text',
            'default_value' => 'Moda con alma, estilo con propósito',
            'placeholder' => 'Ej: Moda con alma, estilo con propósito',
        ),
        array(
            'key' => 'field_historia_paragraph1',
            'label' => 'Párrafo 1',
            'name' => 'historia_paragraph1',
            'type' => 'textarea',
            'rows' => 4,
            'default_value' => 'Pitucas nació de la pasión por vestir a la mujer contemporánea con piezas que hablan de ella: su confianza, su elegancia natural y su forma única de moverse por el mundo.',
            'placeholder' => 'Primer párrafo...',
        ),
        array(
            'key' => 'field_historia_paragraph2',
            'label' => 'Párrafo 2',
            'name' => 'historia_paragraph2',
            'type' => 'textarea',
            'rows' => 4,
            'default_value' => 'Cada prenda está pensada para acompañar tus momentos, desde los más sencillos hasta los más especiales. Tejidos nobles, cortes cuidados y una paleta que respira serenidad. Porque el verdadero lujo es sentirte tú.',
            'placeholder' => 'Segundo párrafo...',
        ),
        array(
            'key' => 'field_historia_button_text',
            'label' => 'Texto del Botón',
            'name' => 'historia_button_text',
            'type' => 'text',
            'default_value' => 'Conoce la marca',
            'placeholder' => 'Ej: Conoce la marca',
        ),
        array(
            'key' => 'field_historia_button_url',
            'label' => 'Enlace del Botón',
            'name' => 'historia_button_url',
            'type' => 'text',
            'default_value' => '',
            'placeholder' => 'Ej: /about',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => 'Campos para la sección Nuestra Historia de la página de inicio',
) );

acf_add_local_field_group( array(
    'key' => 'group_categories_section',
    'title' => 'Categorías Section',
    'fields' => array(
        array(
            'key' => 'field_categories_tabs',
            'label' => 'Categorías',
            'name' => 'categories_tabs',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_cat1_name',
            'label' => 'Categoría 1 - Nombre',
            'name' => 'cat1_name',
            'type' => 'text',
            'default_value' => 'Ropa',
        ),
        array(
            'key' => 'field_cat1_url',
            'label' => 'Categoría 1 - Enlace',
            'name' => 'cat1_url',
            'type' => 'text',
            'default_value' => '#',
        ),
        array(
            'key' => 'field_cat2_name',
            'label' => 'Categoría 2 - Nombre',
            'name' => 'cat2_name',
            'type' => 'text',
            'default_value' => 'Complementos',
        ),
        array(
            'key' => 'field_cat2_url',
            'label' => 'Categoría 2 - Enlace',
            'name' => 'cat2_url',
            'type' => 'text',
            'default_value' => '#',
        ),
        array(
            'key' => 'field_cat3_name',
            'label' => 'Categoría 3 - Nombre',
            'name' => 'cat3_name',
            'type' => 'text',
            'default_value' => 'Calzado',
        ),
        array(
            'key' => 'field_cat3_url',
            'label' => 'Categoría 3 - Enlace',
            'name' => 'cat3_url',
            'type' => 'text',
            'default_value' => '#',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 3,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => 'Campos para la sección de Categorías de la página de inicio',
) );
